### ISSUE TITLE
UA3F设置成功后，应用不生效

### ISSUE THREAD

**Issue by shiqu36** [SunBK201/UA3F#4]
佬，设置完后不生效，这是咋回事哈，下面附上设置图
Log
[2023-12-24 09:43:33][INFO]: UA3F v0.2.0
[2023-12-24 09:43:33][INFO]: Port: 1080
[2023-12-24 09:43:33][INFO]: User-Agent: FFF
[2023-12-24 09:43:33][INFO]: Log level: info
[2023-12-24 09:43:33][INFO]: Listen on 127.0.0.1:1080

![screenshot20231224](https://github.com/SunBK201/UA3F/assets/102450488/d038d8fe-a770-4f27-ae65-336e0baaaaf0)
![screenshot20231224 (1)](https://github.com/SunBK201/UA3F/assets/102450488/547d27fd-a71d-4c79-b64f-1fcf4faf7983)
![screenshot20231224 (2)](https://github.com/SunBK201/UA3F/assets/102450488/389cb1ca-d3d1-4a8d-a724-c24c0e4c419e)
![screenshot20231224 (3)](https://github.com/SunBK201/UA3F/assets/102450488/d4ebe5b1-f0ec-4d23-af1d-669751178d9b)

**Comment by SunBK201** [comment]
Clash 是否启动？

**Comment by shiqu36** [comment]
> Clash 是否启动？

![image](https://github.com/SunBK201/UA3F/assets/102450488/b9a24a4b-8b5d-4848-aa2b-36095d3f3546)
如图，openclash未启动

**Comment by SunBK201** [comment]
UA3F 需要配合 Clash 使用，请阅读 README

**Comment by shiqu36** [comment]
> UA3F 需要配合 Clash 使用，请阅读 README

佬，那clash启动后，配置地址可以选择不填写吗，暂时没用使用clash链接的需求

**Comment by SunBK201** [comment]
没有订阅链接，只需进行下面的配置：
```yaml
proxies:
  - name: "ua3f"
    type: socks5
    server: 127.0.0.1
    port: 1080
    url: http://connectivitycheck.platform.hicloud.com/generate_204
    udp: false

rules:
  - PROCESS-NAME,ua3f,DIRECT
  - NETWORK,udp,DIRECT
  - MATCH,ua3f
```
