### ISSUE TITLE
既然能docker运行了那是否代表可以不对路由器动手脚

### ISSUE THREAD

**Issue by windowBR** [SunBK201/UA3F#45]
如题，我在想是否可以在另外的设备上使用docker运行ua3f，然后PC等客户端使用clash接入做到防校园网检测的作用，如果可以那哪些步骤需要进行变更。
注：此前并未使用过该项目，最近在研究解决方案看到这个项目支持docker就有了如上设想。

**Comment by SunBK201** [comment]
可以的，可以把 UA3F Docker 部署到其他机器，然后让 Clash 将流量重定向 UA3F Docker 中进行 UA 修改

**Comment by windowBR** [comment]
> 可以的，可以把 UA3F Docker 部署到其他机器，然后让 Clash 将流量重定向 UA3F Docker 中进行 UA 修改

我尝试了一下，目前出现了如下情况，具体现象体现为使用浏览器访问墙外网站正常，但无法访问墙内网站如B站
![image](https://github.com/user-attachments/assets/e3cac243-3402-4069-beb9-43e5fc23b0eb)

情况补充：
1. ua3f 已在docker中成功运行
![image](https://github.com/user-attachments/assets/92576276-3ebc-4e58-898d-d2987f29d3a7)
2. mihomo 在同一设备的docker中使用host模式运行，且此前无ua3f需求时使用自己的配置文件一切运行正常，故排除clash内核问题
3. 采用了[ua3f-global-enhance.yaml](https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-global-enhance.yaml) 配置并填入自己的订阅链接，根据需要自行补充了 `allow-lan: true external-controller: '0.0.0.0:9090'`，由于是docker运行，保险起见将 `proxies` 中的 `server` 字段改为了设备内网 IP。

具体修改后的配置文件如下（已隐去代理url）
```
#--------------------------------------------------------------------------------------#
# Written by SunBK201
# https://github.com/SunBK201/UA3F
#--------------------------------------------------------------------------------------#
mixed-port: 7890
allow-lan: true
external-controller: '0.0.0.0:9090'
#--------------------------------------------------------------------------------------#
ipv6: false
mode: rule
#--------------------------------------------------------------------------------------#
dns:
#--------------------------------------------------------------------------------------#
proxies:
  - name: "ua3f"
    type: socks5
    server: 192.168.123.30
    port: 1080
    url: http://connectivitycheck.platform.hicloud.com/generate_204
    udp: false
#--------------------------------------------------------------------------------------#
proxy-providers:
  Global-ISP:
    type: http
    url: "<***手动打码***>"
    interval: 3600
    path: "./Proxy-Providers/Global-ISP.yaml"
    health-check:
      enable: true
      interval: 600
      url: http://1.1.1.1/generate_204
#--------------------------------------------------------------------------------------#
proxy-groups:
  - name: "Switch"
    type: select
    proxies:
      - Fallback
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Fallback"
    type: fallback
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - USA
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Global-ISP"
    type: select
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "CN"
    type: select
    proxies:
      - ua3f
    url: http://connectivitycheck.platform.hicloud.com/generate_204
    interval: 300
  - name: "Netflix"
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - USA
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Bahamut"
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - USA
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "HongKong"
    type: select
    filter: "^(?!.*?(Premium)).*(香港|Hong Kong|HK)"
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Taiwan"
    type: select
    filter: "^(?!.*?(Premium)).*(台湾|Taiwan|TW)"
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Singapore"
    type: select
    filter: "^(?!.*?(Premium)).*(新加坡|Singapore|SG)"
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "Japan"
    type: select
    filter: "^(?!.*?(Premium)).*(日本|Japan|JP)"
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
  - name: "USA"
    type: select
    filter: "^(?!.*?(Premium)).*(美国|USA|US)"
    use:
      - Global-ISP
    url: http://1.1.1.1/generate_204
    interval: 300
#--------------------------------------------------------------------------------------#
rules:
  # Tencent
  - DOMAIN-KEYWORD,wx,Switch
  - DOMAIN-KEYWORD,qq,Switch
  - DOMAIN-KEYWORD,weixin,Switch
  - DOMAIN-KEYWORD,wechat,Switch
  - DOMAIN-KEYWORD,tencent,Switch
  # Personal Define
  - DOMAIN,speed.cloudflare.com,CN
  - DOMAIN-SUFFIX,test-ipv6.com,CN
  - DOMAIN-SUFFIX,httpbin.org,CN
  # Unbreak
  - RULE-SET,Unbreak,CN
  # Apple
  - RULE-SET,Apple,CN
  # Microsoft
  - RULE-SET,Microsoft,CN
  # Nintendo
  - RULE-SET,Nintendo,Switch
  # Notion
  - DOMAIN,http-inputs-notion.splunkcloud.com,Switch
  - RULE-SET,Notion,Switch
  # Steam
  - DOMAIN-SUFFIX,steamcommunity.com,Switch
  - DOMAIN,avatars.akamai.steamstatic.com,Switch
  - DOMAIN,api.steampowered.com,Switch
  - DOMAIN,store.steampowered.com,Switch
  - RULE-SET,SteamCN,CN
  # Telegram
  - RULE-SET,Telegram,Switch
  # Spotify
  - DOMAIN,open.spotify.com,Switch
  - DOMAIN-SUFFIX,akamaized.net,CN
  - DOMAIN-SUFFIX,spotify.com,CN
  - DOMAIN-SUFFIX,spotifycdn.com,CN
  - DOMAIN-SUFFIX,scdn.co,CN
  - DOMAIN-SUFFIX,branch.io,CN
  - RULE-SET,Spotify,CN
  # Streaming
  - DOMAIN,anime1.me,Switch
  - DOMAIN-SUFFIX,anime1.me,CN
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Bahamut,Bahamut
  - RULE-SET,Streaming,Switch
  # Global Domain
  - DOMAIN-SUFFIX,imap.gmail.com,Switch # Gmail
  - DOMAIN-SUFFIX,smtp.gmail.com,Switch # Gmail
  # China Domain
  - DOMAIN-SUFFIX,ua.233996.xyz,CN
  - DOMAIN-SUFFIX,httpbin.org,CN
  - DOMAIN-SUFFIX,ghproxy.com,CN
  # Global SET
  - RULE-SET,Global,Switch
  # China SET
  - RULE-SET,China,CN
  #---!---DNS-Resolve---!--- #
  #---!---DNS-Resolve---!--- #
  #---!---DNS-Resolve---!--- #
  # GeoIP China
  - GEOIP,CN,CN
  # Local Area Network
  - GEOIP,LAN,DIRECT
  # FINAL
  - MATCH,Switch
#--------------------------------------------------------------------------------------#
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: ./RuleSet/Apple.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./RuleSet/Microsoft.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400
  Nintendo:
    type: http
    behavior: classical
    path: ./RuleSet/Nintendo.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Nintendo/Nintendo.yaml
    interval: 86400
  Notion:
    type: http
    behavior: classical
    path: ./RuleSet/Notion.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Notion/Notion.yaml
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    path: ./RuleSet/SteamCN.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    path: ./RuleSet/Spotify.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    path: ./RuleSet/Bahamut.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: domain
    path: ./RuleSet/Streaming.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml
    interval: 86400
  Global:
    type: http
    behavior: domain
    path: ./RuleSet/Global.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Domain.yaml
    interval: 86400
  China:
    type: http
    behavior: domain
    path: ./RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China_Domain.yaml
    interval: 86400
#--------------------------------------------------------------------------------------#
parsers:
#--------------------------------------------------------------------------------------#
```
